if(EXISTS "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/04/Google_Tests_run_template[1]_tests.cmake")
  include("/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/04/Google_Tests_run_template[1]_tests.cmake")
else()
  add_test(Google_Tests_run_template_NOT_BUILT Google_Tests_run_template_NOT_BUILT)
endif()
