if(EXISTS "/mnt/c/Users/илья/Desktop/c++_for_kfu/3hw/homeWork/05/Google_Tests_run_template1[1]_tests.cmake")
  include("/mnt/c/Users/илья/Desktop/c++_for_kfu/3hw/homeWork/05/Google_Tests_run_template1[1]_tests.cmake")
else()
  add_test(Google_Tests_run_template1_NOT_BUILT Google_Tests_run_template1_NOT_BUILT)
endif()
